### ISSUE TITLE
Overlap of inputs

### ISSUE THREAD

**Issue by vScherb** [GerRudi/SimpleR-RotMG#2]
Some inputs in Settings do overlap as in the image below `Open Menu` and `Window name`.

![image](https://user-images.githubusercontent.com/31130966/32985143-1f82b8ea-ccb4-11e7-8e74-f749feafe89a.png)

**Comment by GerRudi** [comment]
<img src="https://i.imgur.com/2kU1cfz.png"/>

Same here, looks good for me, please respond with details about your setup.

**Comment by vScherb** [comment]
Will be discussed in #3
