### ISSUE TITLE
Remove the executable files from git

### ISSUE THREAD

**Issue by vScherb** [GerRudi/SimpleR-RotMG#23]
The executable files are located in the git repository.
It is not good to track them with the version control system.
Is this necessary or can it be removed without any impact?

**Comment by GerRudi** [comment]
They download the client by downloading a release of this git. I could upload an additional zip for each release, containing only the relevant files + binaries (did that first), but I'm unable to track the traffic (downloads) of those additional zips. 
It's nice to have the binaries archived from every release. 

If you have a better solution, let me know.
