### ISSUE TITLE
Version selector wider range

### ISSUE THREAD

**Issue by vScherb** [GerRudi/SimpleR-RotMG#3]
The version selector shows all available versions to download.
Not everything of the select can be read.
![image](https://user-images.githubusercontent.com/31130966/32985166-acba3aa8-ccb4-11e7-9fce-1dc2e9ed0f7f.png)

**Comment by GerRudi** [comment]
<img src="https://i.imgur.com/bFSyhXi.png" /> looks good for me, please mention a few specs (Monitor, resolution, OS, ... So I can look into this.

**Comment by vScherb** [comment]
Okays seems to be a problem with my setup #2 is the same issue as here.
OS: Windows 10
Resolution on the desktop where it was tested: 3840 x 2160

The next time i try to implement something with the default MetroUDF and look if this problem still exists.
