### ISSUE TITLE
Line 3835 Error: Subscript used on non-accessible variable.

### ISSUE THREAD

**Issue by schjoshy** [GerRudi/SimpleR-RotMG#32]
After days of enjoying this script [kudos], I came in to find an error today [see below]. 

![image](https://user-images.githubusercontent.com/18330111/35523269-1260f92a-04e4-11e8-9a69-370531a74b73.png)

Did some digging in the source and found that the error is due to http://testing.realmofthemadgod.com/index.html not being accessible from my network currently. Dunno if it is down or what. 

```
>"C:\Program Files (x86)\AutoIt3\SciTE\..\autoit3.exe" /ErrorStdOut "C:\Users\Josh\Desktop\SimpleR-RotMG-1.2.0\source\SimpleR.au3"    
"C:\Users\Josh\Desktop\SimpleR-RotMG-1.2.0\source\SimpleR.au3" (739) : ==> Subscript used on non-accessible variable.:
$SWF[1][0] = ("http://testing.realmofthemadgod.com/AGCLoader" & $v2[0] & ".swf")
$SWF[1][0] = ("http://testing.realmofthemadgod.com/AGCLoader" & $v2^ ERROR
```

As precise as a mallet in a surgery, I commented out lines 739 and 740 to get me back up and running in the mean time as the primary site appears to work fine.

**Comment by vScherb** [comment]
When I try to access the index.html you linked i get a "Error: not found" page.

- With your fix of commenting the lines out the lines 739 and 740 what is the content of `$v2` at that moment?
- Would it be enough to check for an `IsArray` together with an `UBound` check?
  - What could be done in the case it does not fullfil these checks?

Can you let us know if this issue persists and the provided fix is permanent.
When you think these lines can be commented out and improve the experience for other users, you can create a PR with further information.

**Comment by vScherb** [comment]
Thank you for the notice @schjoshy 
Does the current dev-branch fix your issue completely?

The binaries will be published soon after a first test.

**Comment by GerRudi** [comment]
Thanks a lot to both of you, the [Hotfix](https://github.com/GerRudi/SimpleR-RotMG/releases/tag/v1.2.1) is now live!
