### ISSUE TITLE
Use official permalink to grab version

### ISSUE THREAD

**Issue by GerRudi** [GerRudi/SimpleR-RotMG#36]
No need for regex anymore. 
Deca now provides an always up-to-date link via https://realmofthemadgodhrd.appspot.com/client 
(As announced with [patch X.22.0](https://www.reddit.com/r/RotMG/comments/7ui6v3/patch_x220_gday_oryx/))

**Comment by vScherb** [comment]
When can this be implemented?
Is there a similar solution for the beta program of RotMG?

**Comment by GerRudi** [comment]
I don't see a reason to keep the old solutions and I think they should be removed completely. 
Even as a fallback - if the official link doesn't work, the fallback won't work either. 

As announced today, there's also a link for the testing server: http://testing.realmofthemadgod.com/client 
The testing server goes public tomorrow. I can't even confirm that the old implementation is still working (see error in v1.2.0), because it hasn't been available for the public in over two years. 
To make sure the testing server works, we should update to the official solution asap.

**Comment by GerRudi** [comment]
Devs responded - https://rotmgtesting.appspot.com/client is working, will try to push hotfix soon.

**Comment by vScherb** [comment]
There are three kinds of starting the game:
1. Play regularly
    - get the swf from [https://realmofthemadgodhrd.appspot.com/client](https://realmofthemadgodhrd.appspot.com/client)
    - play with the full-client (AssembleeGameClient)
2. Play on testing
    - get the swf from [https://rotmgtesting.appspot.com/client](https://rotmgtesting.appspot.com/client)
    - play with the full-client (AssembleeGameClient)
3. Play on production with Kongregate
    - get the current version from the [version.txt](http://www.realmofthemadgod.com/version.txt)
    - play with the load on demand client (AGCLoader)

This will be implemented and pushed for the new minor version.

@GerRudi you see any additions to this or is this correct and can be implemented?

**Comment by GerRudi** [comment]
Looks good

**Comment by vScherb** [comment]
Will be closed when it gets merged into master with a new release.

**Comment by vScherb** [comment]
@GerRudi can this issue be closed now?
#41 got merged and was released with version 1.2.3 or does it depend on the referenced issue #45?

**Comment by GerRudi** [comment]
Fixed in v1.2.3
