### ISSUE TITLE
Unable to load language error

### ISSUE THREAD

**Issue by GerRudi** [GerRudi/SimpleR-RotMG#45]
Fix: push update for official permalink earlier. (https://www.realmofthemadgod.com/client)

As described in #36 

Reason is probably because of switch to https on the main site with Patch X.27.0.0

**Comment by vScherb** [comment]
@GerRudi You wrote in the change notes for 1.2.3:
`Fix: Unable to load language error`

So is this still an issue or fixed already as I saw nothing in the merge in #46?

**Comment by GerRudi** [comment]
Fixed.
