### ISSUE TITLE
Add proper fix for downloading Flash Projector

### ISSUE THREAD

**Issue by GerRudi** [GerRudi/SimpleR-RotMG#47]
Adobe decided to remove all old flash projector downloads. 

Used to be available via https://fpdownload.macromedia.com/pub/flashplayer/updaters/30/flashplayer_30_sa.exe
https://fpdownload.macromedia.com/pub/flashplayer/updaters/29/flashplayer_29_sa.exe
...

Only way to still get the old versions is via the [Flash Player Archives](https://helpx.adobe.com/flash-player/kb/archived-flash-player-versions.html#FlashPlayerarchives). 
-> One archive is 400+ MB, instead of just 5 MB for the projector file! 

Main issue: 
There's currently no function that checks for the latest flash projector version on https://www.adobe.com/support/flashplayer/debug_downloads.html - currently it is hardcoded to flashplayer_30_sa.exe. 
-> As soon as a new version gets released, the old one will be gone and no longer work -> hotfix needed to increment flash player version by 1. 
Therefore it should be top priority to always grab the latest version. 
Lower priority: add possibility to download older flash projector versions again.

**Comment by vScherb** [comment]
https://github.com/GerRudi/SimpleR-RotMG/blob/3867f900e321f91ccb05054e7b647643e25b5885/source/Include/InitialSetup.au3#L72

**Comment by vScherb** [comment]
Closed included in release [Version 1.2.4](https://github.com/GerRudi/SimpleR-RotMG/releases/tag/v1.2.4)
