### ISSUE TITLE
Compiler warnings in SimpleR

### ISSUE THREAD

**Issue by vScherb** [GerRudi/SimpleR-RotMG#6]
When compiling SimpleR a lot of warnings pop up.
Most of them seem to be of `possibly used before declaration.` type.

The other warnings are generated by the Au3Stripper with the following warning:
`StripOnly/StripFunc Error: Found Call() statement using unsolvable Func, which will/could lead to removal of Funcs that are used by this Function.`

This should be of no concern, these warnings are located in the metroudf requirements.

**Comment by GerRudi** [comment]
Will be fixed with 0043dce17da036cc3661f54d70bc6ab9b87bdf18

**Comment by GerRudi** [comment]
Warnings fixed with #17 - rest is from metroUDF
